In [11]:
import numpy as np
import math
from spyder_kernels.utils.lazymodules import numpy

In [12]:
# create an array

x = np.array([[1,2,3],[4,5,6],[7,8,9]])  # A 3x3 array
y = np.random.randn(3, 3)  # A 3x3 array randomly generated
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.13695709  1.05136339 -0.94662131]
 [ 1.08819856  0.34335449 -1.76478214]
 [ 0.59635437  0.42076399 -0.23375955]]


In [13]:
# Here we're printing the dimensions of the matrices

print(np.shape(x))
print(np.shape(y))

(3, 3)
(3, 3)


In [14]:
# Here we're printing the number of components in each matrix

print(np.size(x))
print(np.size(y))

9
9


In [16]:
# Here we will print more array attributes
# Notice the syntax 'x.method' we could have done this for size and shape as well

print(x.ndim)  # Number of dimensions/axes x
print(y.ndim)  # Number of dimensions/axes y

2
2


In [17]:
# Here we will identify the type of data
print(x.dtype, y.dtype)

# Here we print the number of bytes of each object
print(x.nbytes, y.nbytes)

int32 float64
36 72
