In [1]:
import numpy as np

In [2]:
# First, a simple 2 x 3 array
basic_array = np.array([[1, 2, 3], [4, 5, 6]])
print(basic_array)
print(basic_array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
# An array of one
ones_array = np.ones(3)
print(ones_array)

[1. 1. 1.]


In [6]:
# Same thing, but zeroes
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [48]:
# We will now create a diagonal array
diag_array = np.diag([1, 2, 3])
print(diag_array)

# Same idea, but in echelon form
echelon_array = np.diag([1, 1, 1])
print(echelon_array)

# We can also do this by using the identity function
np.identity(6)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
# An array of evenly spaced values, from 0 to 6, numbers 2 apart
# start, end, spacing
even_space_array = np.arange(0, 8, 2)
print(even_space_array)

[0 2 4 6]


In [18]:
# Now, instead of the increment, we will define the number of array components
# start, end, number of components
linear_array = np.linspace(0, 10, 20)
print(linear_array)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [30]:
# Now an array of values that are logarithmically spaced
log_space_array = np.logspace(0, 120, 20)
print(log_space_array)

[1.00000000e+000 2.06913808e+006 4.28133240e+012 8.85866790e+018
 1.83298071e+025 3.79269019e+031 7.84759970e+037 1.62377674e+044
 3.35981829e+050 6.95192796e+056 1.43844989e+063 2.97635144e+069
 6.15848211e+075 1.27427499e+082 2.63665090e+088 5.45559478e+094
 1.12883789e+101 2.33572147e+107 4.83293024e+113 1.00000000e+120]


In [34]:
# Creating a meshgrid
# See 02-mesh-grids.ipynb for more information on why this is useful

mesh_array_one = np.meshgrid(np.linspace(0, 10, 5))
mesh_array_two = np.meshgrid(np.linspace(0, 10, 5), np.linspace(10, 20, 5))
print(mesh_array_one)
print("---")
print(mesh_array_two)

[array([ 0. ,  2.5,  5. ,  7.5, 10. ])]
---
[array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ]]), array([[10. , 10. , 10. , 10. , 10. ],
       [12.5, 12.5, 12.5, 12.5, 12.5],
       [15. , 15. , 15. , 15. , 15. ],
       [17.5, 17.5, 17.5, 17.5, 17.5],
       [20. , 20. , 20. , 20. , 20. ]])]


In [41]:
# We will now use a function to define the values of an array

# Here we define a function
def quad_indices(i, j): 
	return i**j

# Now the array
# func_array = np.fromfunction(lambda i, j: x_func[i, j], (5, 5))
shape = (2, 4) # Shape of the output array 
quad_array = np.fromfunction(quad_indices, shape, dtype=float)
print(quad_array)

[[1. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [44]:
# A random array
random_array = np.random.random(3)
print(random_array)

[0.2467424  0.49077642 0.20716243]


In [47]:
# Fill an array with constant values
empty_array = np.empty(3)
print(empty_array)
empty_array.fill(4.0)
print(empty_array)

[0. 0. 0.]
[4. 4. 4.]
