In this file, we define an array and then use its properties to create other arrays

In [4]:
import numpy as np

first_array = np.empty(4)
first_array


array([2.12199579e-314, 1.33897934e-311, 7.90505033e-321, 6.95187041e-310])

In [8]:
second_array = np.empty_like(first_array)
second_array

array([2.12199579e-314, 1.33897934e-311, 7.90505033e-321, 6.95187041e-310])

In [9]:
third_array = np.ones_like(first_array)
third_array

array([1., 1., 1., 1.])

In [10]:
fourth_array = np.zeros_like(first_array)
fourth_array

array([0., 0., 0., 0.])

In [11]:
fifth_array = np.full_like(first_array, 5)
fifth_array

array([5., 5., 5., 5.])

In [13]:
sixth_array = np.stack((first_array, second_array, third_array, fifth_array, fifth_array))
sixth_array

array([[2.12199579e-314, 1.33897934e-311, 7.90505033e-321,
        6.95187041e-310],
       [2.12199579e-314, 1.33897934e-311, 7.90505033e-321,
        6.95187041e-310],
       [1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000],
       [5.00000000e+000, 5.00000000e+000, 5.00000000e+000,
        5.00000000e+000],
       [5.00000000e+000, 5.00000000e+000, 5.00000000e+000,
        5.00000000e+000]])

In [15]:
seventh_array = np.full_like(sixth_array, 32.8)
seventh_array

array([[32.8, 32.8, 32.8, 32.8],
       [32.8, 32.8, 32.8, 32.8],
       [32.8, 32.8, 32.8, 32.8],
       [32.8, 32.8, 32.8, 32.8],
       [32.8, 32.8, 32.8, 32.8]])