In [14]:
import numpy as np

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# The np.eye function will create an array similar to identity, except there is an optional offset as the next couple examples will show

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [18]:
# Here we will create a diagonal
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
# Here we will use the same function, but give arange() as its arg
# What this will do is create a diagonal of the arange() array's arguments
np.arange(1, 20, 3)
np.diag(np.arange(1, 20, 3))

array([[ 1,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0,  0],
       [ 0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0, 16,  0],
       [ 0,  0,  0,  0,  0,  0, 19]])