In [1]:
import numpy as np

In [8]:
# Make a 1D array
array = np.random.rand(6)
print(array)

[0.37203338 0.13423913 0.89971417 0.95371167 0.61220621 0.49919804]


In [9]:
# Select an element in the array
array[2]  # The third element

0.8997141735714616

In [10]:
# The second to last element
array[-2]

0.6122062051557977

In [13]:
# Elements from the second and ending at the 5th
array[1:5]

array([0.13423913, 0.89971417, 0.95371167, 0.61220621])

In [18]:
# Select all elements
array[:]  # Method 1

array([0.37203338, 0.13423913, 0.89971417, 0.95371167, 0.61220621,
       0.49919804])

In [22]:
# Elements from the third through the end
array[2:]

array([0.89971417, 0.95371167, 0.61220621, 0.49919804])

In [23]:
# Elements two through 6, at interval 2
array[1:7:2]

array([0.13423913, 0.95371167, 0.49919804])

In [24]:
# All elements in reverse order
array[::-1]

array([0.49919804, 0.61220621, 0.95371167, 0.89971417, 0.13423913,
       0.37203338])