In [1]:
import numpy as np

In [9]:
elements = np.arange(100)
array = elements.reshape(10,10)
print(array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
# Index the third column
array[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [11]:
# Index the fourth row
array[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [12]:
# Indicate a block of the array we want to slice
array[:2, :2]

array([[ 0,  1],
       [10, 11]])

In [17]:
# A central-ish region of the array
array[2:8, 2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74]])

In [19]:
# A single value
array[2:3, 6:7]

array([[26]])

In [20]:
# Every fourth element
array[::4, ::4]

array([[ 0,  4,  8],
       [40, 44, 48],
       [80, 84, 88]])