In [16]:
# Let's build some arrays to reshape and resize

# Import numpy
import numpy as np

# Three arrays with 10 components 
vector_1 = np.linspace(0, 20, 10)  # An array of 10 components, defined linearly from 0 to 20
vector_2 = np.arange(1, 11, 1)  # An array of 10 components, arranged from 1 to 10 
vector_3 = np.random.random(10)  # 10 random floating point numbers

# Check our work
print(vector_1)
print(vector_2)
print(vector_3)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
[ 1  2  3  4  5  6  7  8  9 10]
[0.22118817 0.48437007 0.55329792 0.83237862 0.93580501 0.22088158
 0.64784553 0.43637446 0.06708503 0.468994  ]


In [74]:
# Now we'll create arrays with more than one dimension using .reshape()
array_1 = np.random.random(10).reshape(5, 2)  # A random array with 5 rows and 2 columns
array_2 = vector_1.reshape(5, 2)  # An array with shape (5, 2) formed from the first vector above
array_3 = vector_2.reshape(5, 2)  # an array with shape (5, 2) formed from the second vector above

# Check our work
print(array_1)
print("----------\n")
print(array_2)
print("----------\n")
print(array_3)

[[0.77064281 0.57802121]
 [0.40343241 0.63622217]
 [0.31428768 0.7716268 ]
 [0.37401065 0.39318827]
 [0.4405784  0.13360405]]
----------

[[ 0.          2.22222222]
 [ 4.44444444  6.66666667]
 [ 8.88888889 11.11111111]
 [13.33333333 15.55555556]
 [17.77777778 20.        ]]
----------

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [73]:
# Now we'll convert them back with .flatten()
flat_1 = array_1.flatten()  # Our first array of (5, 2) flatted back to a vector
flat_2 = array_2.flatten()  # Our second array of (5, 2) flatted back to a vector
flat_3 = array_3.flatten()  # Our third array of (5, 2) flatted back to a vector

# Check our work
print(flat_1)
print("----------\n")
print(flat_2)
print("----------\n")
print(flat_3)

[0.77157778 0.22309122 0.07787632 0.11238573 0.92743274 0.59835615
 0.40094047 0.02479406 0.77498306 0.87332346]
----------

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
----------

[ 1  2  3  4  5  6  7  8  9 10]


In [72]:
reshaped_for_squeeze = array_1.reshape(10, 1)  # Reshaping an array so we have a dimension to squeee out
squeezed_1 = np.squeeze(reshaped_for_squeeze)  # The dimension squeezed out

# Check our work
print(f"Reshaped for squeeing: \n{reshaped_for_squeeze.shape}")
print("----------\n")
print(f"The shape after squeezing: \n{squeezed_1.shape}")
print("----------\n")
print(f"The reshaped array: \n{reshaped_for_squeeze}")
print("----------\n")
print(f"The squeezed array: \n{squeezed_1}")

Reshaped for squeeing: 
(10, 1)
----------

The shape after squeezing: 
(10,)
----------

The reshaped array: 
[[0.77157778]
 [0.22309122]
 [0.07787632]
 [0.11238573]
 [0.92743274]
 [0.59835615]
 [0.40094047]
 [0.02479406]
 [0.77498306]
 [0.87332346]]
----------

The squeezed array: 
[0.77157778 0.22309122 0.07787632 0.11238573 0.92743274 0.59835615
 0.40094047 0.02479406 0.77498306 0.87332346]


In [49]:
# Here we're going to add an axis to the arrays we squeezed

add_dims_1 = squeezed_1[:, np.newaxis]  # Add a columns axis
print(add_dims_1.shape)
print("----------\n")

add_dims_1 = reshaped_for_squeeze[np.newaxis,:]  # Add a rows axis
print(add_dims_1.shape)
print("----------\n")

print(add_dims_1)

(10, 1)
(1, 10, 1)
[[[0.77157778]
  [0.22309122]
  [0.07787632]
  [0.11238573]
  [0.92743274]
  [0.59835615]
  [0.40094047]
  [0.02479406]
  [0.77498306]
  [0.87332346]]]


In [59]:
# Now we're going to flatten out the array and transpose it into a row vector

flat = add_dims_1.flatten()  # Flatten the array
transpose_dims = flat.transpose()  # Transpose the array

# Check our work
print(transpose_dims)
print("----------\n")
print(transpose_dims.shape)

[0.77157778 0.22309122 0.07787632 0.11238573 0.92743274 0.59835615
 0.40094047 0.02479406 0.77498306 0.87332346]
(10,)


In [62]:
# Now we will build some arrays by stacking the vectors we made earlier

stack_1 = np.stack([vector_1, vector_2, vector_3])  # Stack on top of each other
stack_2 = np.hstack([vector_1, vector_2, vector_3])  # Stack column-wise
stack_3 = np.vstack([vector_1, vector_2, vector_3])  # Stack on top of each other

In [65]:
stack_1

array([[ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  7.        ,  8.        ,  9.        , 10.        ],
       [ 0.22118817,  0.48437007,  0.55329792,  0.83237862,  0.93580501,
         0.22088158,  0.64784553,  0.43637446,  0.06708503,  0.468994  ]])

In [69]:
stack_2

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ,
        1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
        6.        ,  7.        ,  8.        ,  9.        , 10.        ,
        0.22118817,  0.48437007,  0.55329792,  0.83237862,  0.93580501,
        0.22088158,  0.64784553,  0.43637446,  0.06708503,  0.468994  ])

In [70]:
stack_3

array([[ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  7.        ,  8.        ,  9.        , 10.        ],
       [ 0.22118817,  0.48437007,  0.55329792,  0.83237862,  0.93580501,
         0.22088158,  0.64784553,  0.43637446,  0.06708503,  0.468994  ]])

In [77]:
 # Here we will stack arrays index by index. 
 stacked_depth_wise = np.dstack([vector_1, vector_2])
 print(stacked_depth_wise.shape)  # We can see here we have a three dimensional arra 1x10x2
 print(stacked_depth_wise)

(1, 10, 2)
[[[ 0.          1.        ]
  [ 2.22222222  2.        ]
  [ 4.44444444  3.        ]
  [ 6.66666667  4.        ]
  [ 8.88888889  5.        ]
  [11.11111111  6.        ]
  [13.33333333  7.        ]
  [15.55555556  8.        ]
  [17.77777778  9.        ]
  [20.         10.        ]]]
