In [105]:
# Let's build some arrays to reshape and resize

# Import numpy
import numpy as np

# Three arrays with 10 components 
vector_1 = np.linspace(0, 20, 10)  # An array of 10 components, defined linearly from 0 to 20
vector_2 = np.arange(1, 11, 1)  # An array of 10 components, arranged from 1 to 10 
vector_3 = np.random.random(10)  # 10 random floating point numbers

# Check our work
print(vector_1)
print(vector_2)
print(vector_3)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
[ 1  2  3  4  5  6  7  8  9 10]
[0.64124603 0.77672662 0.91199355 0.99507037 0.56697079 0.21823642
 0.16244722 0.00858628 0.75662858 0.05520535]


In [106]:
# Now we'll create arrays with more than one dimension using .reshape()
array_1 = np.random.random(10).reshape(5, 2)  # A random array with 5 rows and 2 columns
array_2 = vector_1.reshape(5, 2)  # An array with shape (5, 2) formed from the first vector above
array_3 = vector_2.reshape(5, 2)  # an array with shape (5, 2) formed from the second vector above

# Check our work
print(array_1)
print("----------\n")
print(array_2)
print("----------\n")
print(array_3)

[[0.90284068 0.01124383]
 [0.62261175 0.92549201]
 [0.02296227 0.96237681]
 [0.18055486 0.73092842]
 [0.70686273 0.73650059]]
----------

[[ 0.          2.22222222]
 [ 4.44444444  6.66666667]
 [ 8.88888889 11.11111111]
 [13.33333333 15.55555556]
 [17.77777778 20.        ]]
----------

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [107]:
# Now we'll convert them back with .flatten()
flat_1 = array_1.flatten()  # Our first array of (5, 2) flatted back to a vector
flat_2 = array_2.flatten()  # Our second array of (5, 2) flatted back to a vector
flat_3 = array_3.flatten()  # Our third array of (5, 2) flatted back to a vector

# Check our work
print(flat_1)
print("----------\n")
print(flat_2)
print("----------\n")
print(flat_3)

[0.90284068 0.01124383 0.62261175 0.92549201 0.02296227 0.96237681
 0.18055486 0.73092842 0.70686273 0.73650059]
----------

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
----------

[ 1  2  3  4  5  6  7  8  9 10]


In [108]:
reshaped_for_squeeze = array_1.reshape(10, 1)  # Reshaping an array so we have a dimension to squeee out
squeezed_1 = np.squeeze(reshaped_for_squeeze)  # The dimension squeezed out

# Check our work
print(f"Reshaped for squeeing: \n{reshaped_for_squeeze.shape}")
print("----------\n")
print(f"The shape after squeezing: \n{squeezed_1.shape}")
print("----------\n")
print(f"The reshaped array: \n{reshaped_for_squeeze}")
print("----------\n")
print(f"The squeezed array: \n{squeezed_1}")

Reshaped for squeeing: 
(10, 1)
----------

The shape after squeezing: 
(10,)
----------

The reshaped array: 
[[0.90284068]
 [0.01124383]
 [0.62261175]
 [0.92549201]
 [0.02296227]
 [0.96237681]
 [0.18055486]
 [0.73092842]
 [0.70686273]
 [0.73650059]]
----------

The squeezed array: 
[0.90284068 0.01124383 0.62261175 0.92549201 0.02296227 0.96237681
 0.18055486 0.73092842 0.70686273 0.73650059]


In [109]:
# Here we're going to add an axis to the arrays we squeezed

add_dims_1 = squeezed_1[:, np.newaxis]  # Add a columns axis
print(add_dims_1.shape)
print("----------\n")

add_dims_1 = reshaped_for_squeeze[np.newaxis,:]  # Add a rows axis
print(add_dims_1.shape)
print("----------\n")

print(add_dims_1)

(10, 1)
----------

(1, 10, 1)
----------

[[[0.90284068]
  [0.01124383]
  [0.62261175]
  [0.92549201]
  [0.02296227]
  [0.96237681]
  [0.18055486]
  [0.73092842]
  [0.70686273]
  [0.73650059]]]


In [110]:
# Now we're going to flatten out the array and transpose it into a row vector

flat = add_dims_1.flatten()  # Flatten the array
transpose_dims = flat.transpose()  # Transpose the array

# Check our work
print(transpose_dims)
print("----------\n")
print(transpose_dims.shape)

[0.90284068 0.01124383 0.62261175 0.92549201 0.02296227 0.96237681
 0.18055486 0.73092842 0.70686273 0.73650059]
----------

(10,)


In [119]:
# Now we will build some arrays by stacking the vectors we made earlier

stack_1 = np.stack([vector_1, vector_2, vector_3]) # Stack on top of each other

stack_2 = np.hstack([vector_1, vector_2, vector_3])  # Stack column-wise

stack_3 = np.vstack([vector_1, vector_2, vector_3])  # Stack on top of each other

In [112]:
stack_1

array([[0.00000000e+00, 2.22222222e+00, 4.44444444e+00, 6.66666667e+00,
        8.88888889e+00, 1.11111111e+01, 1.33333333e+01, 1.55555556e+01,
        1.77777778e+01, 2.00000000e+01],
       [1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00,
        5.00000000e+00, 6.00000000e+00, 7.00000000e+00, 8.00000000e+00,
        9.00000000e+00, 1.00000000e+01],
       [6.41246032e-01, 7.76726623e-01, 9.11993549e-01, 9.95070373e-01,
        5.66970790e-01, 2.18236418e-01, 1.62447219e-01, 8.58628311e-03,
        7.56628575e-01, 5.52053494e-02]])

In [113]:
stack_2

array([0.00000000e+00, 2.22222222e+00, 4.44444444e+00, 6.66666667e+00,
       8.88888889e+00, 1.11111111e+01, 1.33333333e+01, 1.55555556e+01,
       1.77777778e+01, 2.00000000e+01, 1.00000000e+00, 2.00000000e+00,
       3.00000000e+00, 4.00000000e+00, 5.00000000e+00, 6.00000000e+00,
       7.00000000e+00, 8.00000000e+00, 9.00000000e+00, 1.00000000e+01,
       6.41246032e-01, 7.76726623e-01, 9.11993549e-01, 9.95070373e-01,
       5.66970790e-01, 2.18236418e-01, 1.62447219e-01, 8.58628311e-03,
       7.56628575e-01, 5.52053494e-02])

In [114]:
stack_3

array([[0.00000000e+00, 2.22222222e+00, 4.44444444e+00, 6.66666667e+00,
        8.88888889e+00, 1.11111111e+01, 1.33333333e+01, 1.55555556e+01,
        1.77777778e+01, 2.00000000e+01],
       [1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00,
        5.00000000e+00, 6.00000000e+00, 7.00000000e+00, 8.00000000e+00,
        9.00000000e+00, 1.00000000e+01],
       [6.41246032e-01, 7.76726623e-01, 9.11993549e-01, 9.95070373e-01,
        5.66970790e-01, 2.18236418e-01, 1.62447219e-01, 8.58628311e-03,
        7.56628575e-01, 5.52053494e-02]])

In [115]:
 # Here we will stack arrays index by index. 
 stacked_depth_wise = np.dstack([vector_1, vector_2])
 print(stacked_depth_wise.shape)  # We can see here we have a three-dimensional array 1x10x2
 print(stacked_depth_wise)

(1, 10, 2)
[[[ 0.          1.        ]
  [ 2.22222222  2.        ]
  [ 4.44444444  3.        ]
  [ 6.66666667  4.        ]
  [ 8.88888889  5.        ]
  [11.11111111  6.        ]
  [13.33333333  7.        ]
  [15.55555556  8.        ]
  [17.77777778  9.        ]
  [20.         10.        ]]]


In [116]:
# Here we're going to create a new array from three arrays
new_concat_0 = np.concatenate([vector_1, vector_2, vector_3])
print(new_concat_0)

[0.00000000e+00 2.22222222e+00 4.44444444e+00 6.66666667e+00
 8.88888889e+00 1.11111111e+01 1.33333333e+01 1.55555556e+01
 1.77777778e+01 2.00000000e+01 1.00000000e+00 2.00000000e+00
 3.00000000e+00 4.00000000e+00 5.00000000e+00 6.00000000e+00
 7.00000000e+00 8.00000000e+00 9.00000000e+00 1.00000000e+01
 6.41246032e-01 7.76726623e-01 9.11993549e-01 9.95070373e-01
 5.66970790e-01 2.18236418e-01 1.62447219e-01 8.58628311e-03
 7.56628575e-01 5.52053494e-02]


In [117]:
# Now we will take an array and resize it

new_concat_0.resize(3, 5, refcheck=False)
print(new_concat_0)

[[ 0.          2.22222222  4.44444444  6.66666667  8.88888889]
 [11.11111111 13.33333333 15.55555556 17.77777778 20.        ]
 [ 1.          2.          3.          4.          5.        ]]


In [125]:
# Now a few more useful additional methods, append, insert and delete

# Append
np.append(new_concat_0, new_concat_0, axis=0)  # Let's double up on this array
print("Using append:\n", new_concat_0)
print("----------\n")
# Insert
inserted_val = np.insert(new_concat_0, [0], 9)
print("Inserting a 9:\n", inserted_val)
print("----------\n")
# Delete
del_vals = np.delete(new_concat_0, [0, 1])
print("Deleting first 4 values:\n",del_vals)

Using append:
 [[ 0.          2.22222222  4.44444444  6.66666667  8.88888889]
 [11.11111111 13.33333333 15.55555556 17.77777778 20.        ]
 [ 1.          2.          3.          4.          5.        ]]
----------

Inserting a 9:
 [ 9.          0.          2.22222222  4.44444444  6.66666667  8.88888889
 11.11111111 13.33333333 15.55555556 17.77777778 20.          1.
  2.          3.          4.          5.        ]
----------

Deleting first 4 values:
 [ 4.44444444  6.66666667  8.88888889 11.11111111 13.33333333 15.55555556
 17.77777778 20.          1.          2.          3.          4.
  5.        ]
