In [1]:
import numpy as np

In [6]:
nray = np.random.randn(5,5)
print(nray.shape)
print(nray)

(5, 5)
[[-1.96775065 -0.58697188  0.93751183  0.22540252  0.58070976]
 [-0.64632004 -2.31309508  0.03217225  1.30304711 -0.66432457]
 [-1.00493975  0.38100778  0.18912341  0.43066831 -0.48034508]
 [-0.27770751 -0.57200462  0.14009296 -0.10623619  0.21265623]
 [-0.81917195  0.11629619  1.18048351  0.61950857 -0.87007051]]


In [7]:
ravel = nray.ravel()
print(ravel.shape)
print(ravel)

(25,)
[-1.96775065 -0.58697188  0.93751183  0.22540252  0.58070976 -0.64632004
 -2.31309508  0.03217225  1.30304711 -0.66432457 -1.00493975  0.38100778
  0.18912341  0.43066831 -0.48034508 -0.27770751 -0.57200462  0.14009296
 -0.10623619  0.21265623 -0.81917195  0.11629619  1.18048351  0.61950857
 -0.87007051]


In [11]:
expanded = np.expand_dims(nray, 2)
print(expanded.shape)

(5, 5, 1)


In [12]:
transposed = expanded.transpose()
print(transposed.shape)

(1, 5, 5)


In [13]:
joined = np.concatenate([nray, nray], axis=0)
print(joined.shape)

(10, 5)


In [14]:
deep_join = np.dstack([nray, nray])
print(deep_join.shape)

(5, 5, 2)


In [15]:
summed = np.logical_and(nray, nray).sum()
print(summed)

25


In [18]:
larger = np.resize(nray, [10, 10])
print(larger.shape)

(10, 10)


In [20]:
inserted = np.insert(nray, 0, 12)
print(inserted.shape)
print(inserted)

(26,)
[12.         -1.96775065 -0.58697188  0.93751183  0.22540252  0.58070976
 -0.64632004 -2.31309508  0.03217225  1.30304711 -0.66432457 -1.00493975
  0.38100778  0.18912341  0.43066831 -0.48034508 -0.27770751 -0.57200462
  0.14009296 -0.10623619  0.21265623 -0.81917195  0.11629619  1.18048351
  0.61950857 -0.87007051]
