In [1]:
import numpy as np

In [4]:
new_ray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
h_ray = np.array([4, 5, 6])
v_ray = np.array([[4], [5], [6]])
print(h_ray)
print(v_ray)

[4 5 6]
[[4]
 [5]
 [6]]


In [6]:
b_cast_1 = new_ray + v_ray
b_cast_2 = new_ray + h_ray
print(b_cast_1)
print(" ")
print(b_cast_2)

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
 
[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
