In [1]:
import numpy as np

In [2]:
# First let's create a couple arrays we can work with

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])

In [4]:
# Addition and subtraction

addition = np.add(x, y)
subtraction = np.subtract(x, y)

addition_alt = x + y
subtraction_alt = x - y

print("Addition: \n", addition, "\n", "Addition_alt \n", addition_alt, "\n", "Subtraction: \n",  subtraction, "\n", "Subtraction_alt: \n", subtraction_alt)

Addition: 
 [[ 3  4  5]
 [ 7  8  9]
 [11 12 13]] 
 Addition_alt 
 [[ 3  4  5]
 [ 7  8  9]
 [11 12 13]] 
 Subtraction: 
 [[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]] 
 Subtraction_alt: 
 [[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]]


In [5]:
# Multiplication, division and powers
print("Multiplication")
print(x * 2)
print("\n")

print("Powers")
print(x ** 2)
print("\n")

print("Division")
print(x / 2)
print("\n")

Multiplication
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Powers
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Division
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


