In [1]:
import numpy as np

The various functions and operations in this section are applied element by element in the matrices.

In [9]:
array = np.logspace(3, 10, num=4)
array = array.reshape(2, 2)
print(array)

[[1.00000000e+03 2.15443469e+05]
 [4.64158883e+07 1.00000000e+10]]


In [14]:
# Other trig functions inc: arcos, arcsin, arctan, cosh, sinh, tanh, arcosh, arcsinh, arctanh

cosine = np.cos(np.pi / array)
sine = np.sin(np.pi * array)
tangent = np.tan(np.pi / array)

print(cosine)
print("----- \n")
print(sine)
print("----- \n")
print(tangent)

[[0.99999507 1.        ]
 [1.         1.        ]]
----- 

[[-3.21416646e-13 -9.95262376e-01]
 [ 8.70381533e-01 -2.23936276e-06]]
----- 

[[3.14160299e-03 1.45819814e-05]
 [6.76835619e-08 3.14159265e-10]]


In [18]:
sqrt = np.sqrt(array)
a = np.log(array)
b = np.log2(array)
c = np.log10(array)
print("----- \n")
print(sqrt)
print("----- \n")
print(a)
print("----- \n")
print(b)
print("----- \n")
print(c)

----- 

[[3.16227766e+01 4.64158883e+02]
 [6.81292069e+03 1.00000000e+05]]
----- 

[[ 6.90775528 12.28045383]
 [17.65315238 23.02585093]]
----- 

[[ 9.96578428 17.71694984]
 [25.46811539 33.21928095]]
----- 

[[ 3.          5.33333333]
 [ 7.66666667 10.        ]]
