In [ ]:
# In this file we are going to apply the sigmoid function to an array

In [34]:
# Import the libraries we'll use
import numpy as np
from sklearn.preprocessing import normalize

# Here we're going to build a matrix

# Create some arrays
_first_array = np.linspace(0, 10, 20)
_second_array = np.linspace(10, 20, 20)
_third_array = np.linspace(20, 30, 20)
_fourth_array = np.linspace(40, 50, 20)
_fifth_array = np.linspace(50, 60, 20)

# Stack the arrays together
new_matrix = np.stack((_first_array, _second_array, _third_array, _fourth_array, _fifth_array), axis=1)
print("Our newly created matrix: \n\n", new_matrix)

# Let's normalize the matrix
normal_matrix = normalize(new_matrix, axis=1, norm='l1')

# Let's vectorize the matrix
vector_matrix = normal_matrix.reshape(-1)
print("\n\nOur vectorized matrix: \n\n", vector_matrix)

# Let's now compute the sigmoid function on the vectorized array
s_function = 1 / (1 + np.exp(-new_matrix))
print("\n\nFinally, the matrix after the sigmoid operation\n\n", s_function.reshape(-1))

Our newly created matrix: 

 [[ 0.         10.         20.         40.         50.        ]
 [ 0.52631579 10.52631579 20.52631579 40.52631579 50.52631579]
 [ 1.05263158 11.05263158 21.05263158 41.05263158 51.05263158]
 [ 1.57894737 11.57894737 21.57894737 41.57894737 51.57894737]
 [ 2.10526316 12.10526316 22.10526316 42.10526316 52.10526316]
 [ 2.63157895 12.63157895 22.63157895 42.63157895 52.63157895]
 [ 3.15789474 13.15789474 23.15789474 43.15789474 53.15789474]
 [ 3.68421053 13.68421053 23.68421053 43.68421053 53.68421053]
 [ 4.21052632 14.21052632 24.21052632 44.21052632 54.21052632]
 [ 4.73684211 14.73684211 24.73684211 44.73684211 54.73684211]
 [ 5.26315789 15.26315789 25.26315789 45.26315789 55.26315789]
 [ 5.78947368 15.78947368 25.78947368 45.78947368 55.78947368]
 [ 6.31578947 16.31578947 26.31578947 46.31578947 56.31578947]
 [ 6.84210526 16.84210526 26.84210526 46.84210526 56.84210526]
 [ 7.36842105 17.36842105 27.36842105 47.36842105 57.36842105]
 [ 7.89473684 17.89473684 